core_case_data:
  api:
    url: ${CCD_URL:http://127.0.0.1:4452}

case_document_am.url: ${CASE_DOCUMENT_AM_URL:http://127.0.0.1:4455}

auth:
  idam:
    client:
      baseUrl: ${IDAM_URL:http://127.0.0.1:4501}
  provider:
    service:
      client:
        baseUrl: ${S2S_URL:http://127.0.0.1:4502}

idam:
  url: ${IDAM_URL:http://127.0.0.1:4501}
  urlnew: ${OPEN_ID_IDAM_URL:http://127.0.0.1:5000}
  s2s-auth:
    totp_secret: ${IA_S2S_SECRET:AAAAAAAAAAAAAAAC}
    url: ${S2S_URL:http://127.0.0.1:4502}
  oauth2:
    user:
      email: ia-law-firm-org-sc@fake.hmcts.net
      password: London03
    client:
      id: ccd_gateway
      secret: OOOOOOOOOOOOOOOO
    redirectUrl: ${IA_IDAM_REDIRECT_URI:http://localhost:3002/oauth2/callback}
document_management:
  url: ${DM_STORE_URL:http://dm-store:4506}

idam_token: SET_ME
idam_user_id: 427303d7-5692-3532-9dea-26659ecf3a45
idam_user_role: caseworker


migration.idam.username: ia-law-firm-org-sc@fake.hmcts.net
migration.idam.password: London03
