spring:
  application:
    name: IA Case Creator
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri:  https://idam-web-public.aat.platform.hmcts.net/o
        registration:
          oidc:
            client-id: iac
            client-secret: NDPH6DFQBIPA9UP7

core_case_data:
  api:
    url: https://ccd-data-store-api-ia-case-api-pr-2525.preview.platform.hmcts.net

auth:
  idam:
    client:
      baseUrl: http://idam-api.aat.platform.hmcts.net
  provider:
    service:
      client:
        baseUrl: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal

idam:
  baseUrl: https://idam-web-public.aat.platform.hmcts.net
  redirectUrl: https://ia-case-api-aat.service.core-compute-aat.internal/oauth2/callback
  scope: "openid profile roles"
  api:
    baseUrl: https://idam-web-public.aat.platform.hmcts.net
  s2s-auth:
    totp_secret: NDPH6DFQBIPA9UP7
    secret: NDPH6DFQBIPA9UP7
    name: iac
    url: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal/testing-support/
  user:
    role: WaSystemUser

document_management:
  url: http://dm-store-aat.service.core-compute-aat.internal




case_document_am.url: http://ccd-case-document-am-api-aat.service.core-compute-aat.internal

migration.idam.username: "ia.super.ccd@gmail.com"
migration.idam.password: "AldgateT0wer"